openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  '/api/v1/topics/{topic_id}/posts':
    get:
      summary: 'Get all posts in topic'
      operationId: getAllPostsInTopic
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\Topic] 1'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\Topic] 1'
      tags:
        - Topics
      security: []
    parameters:
      -
        in: path
        name: topic_id
        description: 'The ID of the topic.'
        example: 1
        required: true
        schema:
          type: integer
  /api/v1/topics:
    get:
      summary: 'Get all topics'
      operationId: getAllTopics
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: []
                  links:
                    first: 'http://localhost/api/v1/topics?page=1'
                    last: 'http://localhost/api/v1/topics?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: null
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/v1/topics?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://localhost/api/v1/topics'
                    per_page: 15
                    to: null
                    total: 0
                properties:
                  data:
                    type: array
                    example: []
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost/api/v1/topics?page=1'
                      last:
                        type: string
                        example: 'http://localhost/api/v1/topics?page=1'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: string
                        example: null
                      last_page:
                        type: integer
                        example: 1
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost/api/v1/topics?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost/api/v1/topics'
                      per_page:
                        type: integer
                        example: 15
                      to:
                        type: string
                        example: null
                      total:
                        type: integer
                        example: 0
      tags:
        - Topics
      security: []
    post:
      summary: 'Create a new topic'
      operationId: createANewTopic
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Topics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 70 characters.'
                  example: hwtnibp
                special:
                  type: boolean
                  description: ''
                  example: true
                description:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: 'Iure est ut qui deserunt nobis pariatur.'
              required:
                - name
                - special
      security: []
  '/api/v1/topics/{id}':
    get:
      summary: 'Get a topic'
      operationId: getATopic
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\Topic] 12'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\Topic] 12'
      tags:
        - Topics
      security: []
    put:
      summary: 'Update a topic'
      operationId: updateATopic
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Topics
      security: []
    delete:
      summary: 'Remove a topic'
      operationId: removeATopic
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Topics
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the topic.'
        example: 12
        required: true
        schema:
          type: integer
  /api/v1/posts:
    get:
      summary: 'Get all posts'
      operationId: getAllPosts
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: []
                  links:
                    first: 'http://localhost/api/v1/posts?page=1'
                    last: 'http://localhost/api/v1/posts?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: null
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/v1/posts?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://localhost/api/v1/posts'
                    per_page: 15
                    to: null
                    total: 0
                properties:
                  data:
                    type: array
                    example: []
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost/api/v1/posts?page=1'
                      last:
                        type: string
                        example: 'http://localhost/api/v1/posts?page=1'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: string
                        example: null
                      last_page:
                        type: integer
                        example: 1
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost/api/v1/posts?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost/api/v1/posts'
                      per_page:
                        type: integer
                        example: 15
                      to:
                        type: string
                        example: null
                      total:
                        type: integer
                        example: 0
      tags:
        - Posts
      security: []
    post:
      summary: 'Create new post'
      operationId: createNewPost
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 100 characters.'
                  example: bsjphcstvrfvu
                link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: gdwsyfp
                topic_id:
                  type: string
                  description: ''
                  example: facilis
              required:
                - title
                - topic_id
      security: []
  '/api/v1/posts/{id}':
    get:
      summary: 'Get a post'
      operationId: getAPost
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\Post] 2'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\Post] 2'
      tags:
        - Posts
      security: []
    put:
      summary: 'Update a post'
      operationId: updateAPost
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Posts
      security: []
    delete:
      summary: 'Remove a topic'
      operationId: removeATopic
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Posts
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the post.'
        example: 2
        required: true
        schema:
          type: integer
  '/api/v1/posts/{post_id}/topic':
    get:
      summary: 'Get the topic of a post'
      operationId: getTheTopicOfAPost
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\Post] 8'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\Post] 8'
      tags:
        - Posts
      security: []
    parameters:
      -
        in: path
        name: post_id
        description: 'The ID of the post.'
        example: 8
        required: true
        schema:
          type: integer
  /api/v1/user:
    get:
      summary: 'Get user information'
      operationId: getUserInformation
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  name: Alex
                  email: backtheportal@gmail.com
                  email_verified_at: '2024-06-29T18:08:23.000000Z'
                  locale: en
                  created_at: '2024-06-29T18:08:24.000000Z'
                  updated_at: '2024-06-29T18:08:24.000000Z'
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: Alex
                  email:
                    type: string
                    example: backtheportal@gmail.com
                  email_verified_at:
                    type: string
                    example: '2024-06-29T18:08:23.000000Z'
                  locale:
                    type: string
                    example: en
                  created_at:
                    type: string
                    example: '2024-06-29T18:08:24.000000Z'
                  updated_at:
                    type: string
                    example: '2024-06-29T18:08:24.000000Z'
      tags:
        - 'Auth management'
  /api/v1/images:
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/v1/images/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server Error'
                properties:
                  message:
                    type: string
                    example: 'Server Error'
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the image.'
        example: 7
        required: true
        schema:
          type: integer
tags:
  -
    name: Topics
    description: ''
  -
    name: Posts
    description: ''
  -
    name: 'Auth management'
    description: ''
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
